a='g fmnc wms bgblr rpylqjyrc gr zw fylb. rfyrq ufyr amknsrcpq ypc dmp. bmgle gr gl zw fylb gq glcddgagclr ylb rfyrq ufw rfgq rcvr gq qm jmle. sqgle qrpgle.kyicrpylq() gq pcamkkclbcb. lmu ynnjw ml rfc spj.'
a='map'
a=a.replace('w','y')
a=a.replace('v','x')
a=a.replace('u','w')
a=a.replace('t','v')
a=a.replace('s','u')
a=a.replace('r','t')
a=a.replace('q','s')
a=a.replace('p','r')
a=a.replace('o','q')
a=a.replace('n','p')
a=a.replace('m','o')
a=a.replace('l','n')
a=a.replace('k','m')
a=a.replace('j','l')
a=a.replace('i','k')
a=a.replace('h','j')
a=a.replace('g','i')
a=a.replace('f','h')
a=a.replace('e','g')
a=a.replace('d','f')
a=a.replace('c','e')
a=a.replace('b','d')
a=a.replace('a','c')
a=a.replace('z','b')
a=a.replace('y','a')
a=a.replace('x','z')


print(a)
